version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vendora_db
      POSTGRES_USER: vendora
      POSTGRES_PASSWORD: changeme
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=vendora_db
      - POSTGRES_USER=vendora
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  db_data:
